#FROM debian
#ENV name Manu
#CMD echo "Hello, $name"
#CMD ["zsh", "echo", "Hello, $name"]

FROM ubuntu
#ENTRYPOINT ["top", "-b"]
CMD ["/bin/echo", "test"]

#FROM debian
#ENTRYPOINT ["echo", "les gens"]
#CMD ["nazes"]
#CMD ["echo", "ciao les nazes"]
