#!/bin/bash
host=~/Abathur_root

mkdir -p $host
cp hello.py $host

docker run -id --name=Abathur -p 3000:3000 -v $host:/root python:2-slim
docker exec Abathur pip install Flask
docker exec -e FLASK_APP=/root/hello.py Abathur flask run --host=0.0.0.0 --port=3000
